### ISSUE TITLE
Validate validator valoper address

### ISSUE THREAD

**Issue by JakeHartnell** [CosmWasm/mesh-security#42]
There are a number place where we have to validate an validator operator address, for example:
- https://github.com/CosmWasm/mesh-security/blob/main/contracts/meta-staking/src/contract.rs#L100
- https://github.com/CosmWasm/mesh-security/blob/main/contracts/meta-staking/src/contract.rs#L156
- https://github.com/CosmWasm/mesh-security/blob/main/contracts/mesh-lockup/src/contract.rs#L105

This maybe a good thing to contribute upstream somewhere. Maybe even `cosmwasm_std`?

**Comment by Art3miX** [comment]
I looked into this issue, and initially I thought about hacking it with just replacing the validator prefix with the chain prefix and use `addr_validate`, but I couldn't find a way to get both prefixes for the replace, so probably it won't work without providing the contracts the prefixes externally, which seems like too much for the task in hand.

In meta-staking we can just query the validator and see if it exists, but the delegate/undelegate functions should already check if this validator is valid, so I don't see a point in doing another query, because it should error either way, and obviously it won't work in mesh-lockup unless we do IBC query.

I am not even sure `cosmwasm_std` should handle it, because same chain validator should just error correctly when you try to do something with invalid validator, and this `validator_addr_validate` will only handle its own chain prefix (I assume?).
So in order to validate this, you would still need to pass the other chain prefix.

So the easiest way I see, is just pass and save the prefixes we expect (if `valoper` is always the validator prefix then just pass the chain prefix, but im not sure its the case), replace validator prefix with the saved chain prefix, and do `addr_validate`, this should error if its not valid and we put the validator as `Addr::unchecked`.

There must be a better way of doing this.

**Comment by JakeHartnell** [comment]
Helpful comments here: https://twitter.com/simon_warta/status/1602405114148491274

**Comment by Art3miX** [comment]
> Helpful comments here: https://twitter.com/simon_warta/status/1602405114148491274

from this, I used this library: https://docs.rs/subtle-encoding/latest/subtle_encoding/bech32/index.html
But it says: `NOTE: This implementation is not yet constant time, but we intend to make it such.` so not sure how stable it is to use, but from tests I did it works.

Here is a function to test if an address is valid, but we need the prefix predefined so we can compare against it.
```rust
fn validate_validator_addr(val_prefix: String, validator: String) -> Result<(), ContractError> {
    match bech32::decode(validator) {
        Ok((prefix, _)) => {
            if val_prefix == prefix {
                Ok(())
            } else {
                Err(ContractError::ValidatorAddressInvalid)
            }
        }
        Err(err) => Err(ContractError::ValidatorAddressInvalid),
    }
}
```

Not sure if its enough that we can decode the address and that we compare the prefixes.

**Comment by JakeHartnell** [comment]
Honestly, starting to wonder if this is even worth doing...

**Comment by JakeHartnell** [comment]
After more thought, I'm closing this. Some newer chains won't have `valoper` addresses.

**Comment by 0xekez** [comment]
the process for validating an address seems to be the same for [validators](https://github.com/cosmos/cosmos-sdk/blob/1dad6891e27bb5f797d74301c1ed341661d2d9c2/types/address.go#L324-L343) and [regular accounts](https://github.com/cosmos/cosmos-sdk/blob/1dad6891e27bb5f797d74301c1ed341661d2d9c2/types/address.go#L176-L195) in the SDK. I agree that implementing this probably isn't worth it. string manipulation > custom rust addr validation, and we can validate by making a query as @Art3miX mentions.

**Comment by tejas-kothari** [comment]
You can query the active validator set with the operator address and see if it returns a response. If it doesn't, then you know the operator address is incorrect. 

```rust
deps.querier.query_validator(msg.validator.clone())?.unwrap();
let validator: Addr = Addr::unchecked(msg.validator);
```
